// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get("API_KEY_WEB", fallback: ""),
    appId: dotenv.get("APP_ID_WEB", fallback: ""),
    messagingSenderId: '861239158601',
    projectId: 'grind-d848b',
    authDomain: 'grind-d848b.firebaseapp.com',
    storageBucket: 'grind-d848b.appspot.com',
    measurementId: 'G-4SWLHEPKL3',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get("API_KEY_ANDROID", fallback: ""),
    appId: dotenv.get("API_ID_ANDROID", fallback: ""),
    messagingSenderId: '861239158601',
    projectId: 'grind-d848b',
    storageBucket: 'grind-d848b.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get("API_KEY_IOS", fallback: ""),
    appId: dotenv.get("API_ID_IOS", fallback: ""),
    messagingSenderId: '861239158601',
    projectId: 'grind-d848b',
    storageBucket: 'grind-d848b.appspot.com',
    iosBundleId: 'com.example.workoutApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get("API_KEY_MACOS", fallback: ""),
    appId: dotenv.get("API_ID_MACOS", fallback: ""),
    messagingSenderId: '861239158601',
    projectId: 'grind-d848b',
    storageBucket: 'grind-d848b.appspot.com',
    iosBundleId: 'com.example.workoutApp.RunnerTests',
  );
}
